Rdt over udp
tarihay/Networks pull request #1
Opened 2022-03-30 14:11 UTC by tarihay

2022-04-02 17:05 UTC, dmazhuga requested changes
Нужно немного поправить алгоритм, в целом нормально

2022-04-02 17:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Client.java
> +                        clientSocket.receive(ackSegment);
Было бы лучше сначала получить пакет через clientSocket.receive, а потом по рандому его отбрасывать. Иначе возможно получить этот же пакет позже, несмотря на то, что он должен был быть "отброшен".

2022-04-02 17:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Client.java
> +                HashMap<Integer, String> messages = new HashMap<>();
А нужна ли вообще мапа, если в один момент времени отправляется/подтверждается только одно сообщение?

2022-04-02 17:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Client.java
> +                    else if ((timeSpent >  WAIT_TIME && timeSpent < WAIT_TIME_WITH_RESERVE)) {
Вместо такого измерения таймаута проще использовать clientSocket.setSoTimeout - после этого вызов clientSocket.receive будет блокирующим ровно на это время.

2022-04-02 17:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Server.java
> +                byte[] message = new byte[MAX_BUF_SIZE];
Ограничение на MAX_BUF_SIZE стоит продублировать и в клиенте. Желательно также реализовать сегментацию - т.е. если сообщение больше этого размера, то клиент отправит его кусками.

2022-04-02 17:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Server.java
> +                byte[] buffer = new byte[MAX_BUF_SIZE];
А ещё один буффер зачем?

2022-04-02 17:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Server.java
> +                serverSocket.receive(segment);
На сервере тоже может произойти потеря пакетов - нужно добавить сюда рандом.

2022-04-02 17:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Client.java
> +import org.apache.logging.log4j.LogManager;
Если используешь сторонние библиотеки, то не обойтись без системы сборки (maven, gradle). Иначе не получится запустить твой код локально, не скачав и не подложив библиотеку вручную.

2022-04-03 13:45 UTC, tarihay commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Server.java
> +                byte[] buffer = new byte[MAX_BUF_SIZE];
Во втором буффере я полностью собираю сегмент: в нулевом элементе seq, в первом ack, в >=2 уже лежит сообщение

2022-04-03 14:05 UTC, dmazhuga commented on UDP/src/main/java/ru/nsu/gorin/networks/udp/Server.java
> +                byte[] buffer = new byte[MAX_BUF_SIZE];
У String есть конструкторы с offset, это гораздо эффективнее, чем копировать массив.
Но это, конечно, уже не по алгоритму замечание.

2022-04-09 09:34 UTC, dmazhuga commented on src/main/java/ru/nsu/gorin/networks/udp/Client.java
> +                            clientSocket.close();
Если ты закрываешь сокет, то ты не должен после этого его использовать (после выхода из if идет переотправка). Я вижу, что ты обрабатываешь ошибку, которая выскочит, но более красивый и понятный код будет, если ты просто выйдешь после закрытия сокета.

Либо можно в этом случае просто забить на текущее сообщение, но не закрывать сокет, и дальше пересылать новый ввод из консоли.

2022-04-13 13:05 UTC, dmazhuga approved these changes

2022-04-13 14:20 UTC, merged